
bind-addr ::
bind-port 65353

#
china-dns 223.5.5.5,223.6.6.6
trust-dns 1.1.1.1,1.0.0.1,8.8.8.8,8.8.4.4

#
ipset-name4 chnroute
ipset-name6 chnroute6

#
# no-ipv6

hosts /etc/hosts
cache 4096
cache-stale 86400
cache-refresh 20
cache-db /tmp/chinadns-ng-cache.db
verdict-cache 4096
verdict-cache-db /tmp/chinadns-ng-verdict.db
timeout-sec 5
